### ISSUE TITLE
Playground v0.4

### ISSUE THREAD

**Issue by gubloon** [0xPolygonMiden/examples#169]
Created this issue for planning and tracking Playground v0.4.
```[tasklist]
### Tasks
- [ ] Feature: Integrate Node
- [ ] Feature: Integrate Client
- [ ] Feature: Integrate Compiler
- [ ] Feature: Integrate Tutorials
- [ ] Idea: Intergrate command line
- [ ] Idea: (local)data storage
```

**Comment by Dominik1999** [comment]
I will close this issue and create a GitHub milestone instead
