### ISSUE TITLE
Provide Assembler Instructions 

### ISSUE THREAD

**Issue by Dominik1999** [0xPolygonMiden/examples#43]
We want to provide Assembler instructions with the Playground. Users should be able to have a nice list handy when they code with the Playground. 

A good example is https://www.evm.codes

## Implementation - done is better than perfect
We will start with a second tab that lists all Assembler instructions. We can improve that in the future. The Assembler Tab will have a searchable list (https://www.npmjs.com/package/react-table) and will cover the same information as our docs. We can think of better ways to show the cycle count in the next iteration. 

## ToDo Lists
- [ ] Create a new tab for the Miden Assembler Instructions
- [ ] Bring all Assembler instructions from our docs into necessary format
- [ ] Show Assembler instructions in react table 
- [ ] Create an issue to improve the Instructions table in the future with automated cycle count

**Comment by Dominik1999** [comment]
@Overcastan Do you know a way how to map our Assembly instructions - [here for example ](https://github.com/0xPolygonMiden/miden-vm/blob/main/docs/src/user_docs/assembly/field_operations.md) - into that format:

```
const instructionSet = [
  {
    name: 'Assertions and tests',
    instructions: [
      { name: 'assert', stack_input: '[a, ...]', stack_output: '[...]', cycles: '1' },
      { name: 'assert_eq', stack_input: '[b, a, ...]', stack_output: '[...]', cycles: '1' },
      { name: '...', stack_input: '...', stack_output: '...', cycles: '...' },
    ],
  },
  // More instructions...
]
```

I think a simple python script would do it.

**Comment by bobbinth** [comment]
I think we should probably spend a bit more time on defining the format, and I'm not sure we should tackle this yet.

For example, one of the issues is that the number of cycles frequently depends on the immediate parameter - so, ideally we should provide number of cycles per instruction variant - but this info is not available in the source file.

Similarly, we can probably do a better job of describing stack start state and end state.

**Comment by Overcastan** [comment]
Indeed, it looks like we can generate such a file using a simple python script, if we allow the use of a variable number of cycles in the description of the operation. But I agree with Bobbin, perhaps we can find a more suitable format. 

I'm not sure yet how we can improve the description of stack states, but the problem of a variable number of cycles is a little clearer to me. If I understand correctly, most of these situations occur when adding an immediate value to the stack, and if it is `1` (or `Felt::ONE`), we use not one operation, but two. It seems to me that we can also handle such cases with a script. 
But there are still field ops and stack manipulation ops, for which the calculation of the number of cycles will have to be done manually, which we would like to avoid.

**Comment by Dominik1999** [comment]
Ok, that makes sense. So I am collecting some options.

### Option 1 - show it like evm.codes
So, in my opinion, the way how this page shows the instructions is quite cool: https://www.evm.codes/
They show the code and the stack; you can expand every single command to get more info. We don't have the info to the extent that they are showing it at the moment. But we could work on that, which definitely consumes some time.

### Option 2 - only link to our docu and show info on the playground
Another option is to simply put a link to our docs for developers to use for now. Instead of showing the instructions, we could show more info about the playgrounds and the program. One feedback I got, is that people don't understand how to use the playground. There is a description in the README, but not on the playground. So we can simply have little pictures or animations explaining what is happening and why. 

### Option 3 - ?


@grjte what do you think?

I think also @hackaugusto had a nice way of showing stack changes in Assembler.

**Comment by hackaugusto** [comment]
Hey, since I was pinged I'm going to drop my two cents here :). Here are my opinions:

- When I'm writing assembly, I don't care about the binary instruction format. So it makes sense to have that in the JSON file, but I don't see any benefit for the playground cheat sheet.
- For the file definition:
  - I would use `instruction` instead of `name` (it is just a bit more precise)
  - A Miden instruction doesn't necessarily have a direct mapping to an operation, e.g. `movup.8` is `1` opcode/cycle, `movup.9` is `4` opcodes/cycles. For this reason I would group instructions into general categories, and have the description for them.
  - Miden instructions accept a variable number of arguments, e.g. `drop` accepts `0` arguments, `movup` requires `1` decimal number in the range of `2-15`, `push` requires one or more hex or decimal numbers in the range of a field element. For this reason I would define a group to have a format expression.
  - Some instructions also touch the tape and memory, so that also needs a representation in the file, so I would have values for tape/memory/stack, and keys before/after. I think that what is not touched by the instructions could be omitted from the description

This is the rough outline of the file:

```json
[
  {
     "group": "drop",
     "stack": {"before: "[a, ...]", "after": "[...]"},
     "cycles": {"min": 1, "max": 1},
     "arguments": {"min": 0, "max": 0},
     "description": "drops the element on the top of the stack",
     "instructions": [
       {"instruction": "drop", "cycles": 1, "stack_input": ["a"], "stack_output": [], "description": "drops the element on the top of the stack"},
     ]
  },
  {
     "group": "adv_push",
     "tape": {"before: "[a, ...]", "after": "[...]"},
     "stack": {"before: "[...]", "after": "[a, ...]"},
     "cycles": {"min": 1, "max": 16},
     "arguments": {"min": 1, "max": 1, "range": {"min": 1, "max": 16}},
     "description": "Reads n top elements from the tape to the stack",
     "instructions": [
       {"instruction": "adv_push", "arguments": [1], "cycles": 1, "tape": {"before: "[a, ...]", "after": "[...]"}, "stack": {"before: "[...]", "after": "[a, ...]"}, "description": "Reads the top element from the tape to the stack"},
       {"instruction": "adv_push", "arguments": [2], "cycles": 2, "tape": {"before: "[a, b, ...]", "after": "[...]"}, "stack": {"before: "[...]", "after": "[b, a, ...]"}, "description": "Reads the top two elements from the tape to the stack"},
       ...
     ]
  },
  {
     "group": "movup",
     "stack": {"before: "[..., a]", "after": "[a, ...]"},
     "cycles": {"min": 1, "max": 4},
     "arguments": {"min": 1, "max": 1, "range": {"min": 2, "max": 15}}
     "description": "move the element on the nth stack position to the top of the stack",
     "instructions": [
       {"instruction": "movup", "arguments": [8], "cycles": 1, "stack": {"before": ["0", "1", "2", "3", "4", "5", "6", "7", "a"], "after": ["a", "0", "1", "2", "3", "4", "5", "6", "7"]}, "description": "moves the 8th stack element to the 0th position"},
       {"instruction": "movup", "arguments": [9], "cycles": 4, "stack": {"before": ["0", "1", "2", "3", "4", "5", "6", "7", "8", "a"], "after": ["a", "0", "1", "2", "3", "4", "5", "6", "7", "8"]}, "description": "moves the 9th stack element to the 0th position"},
       ...
     ]
  },
  {
     "group": "push",
     "stack": {"before: "[]", "after": "[a, b, c, ...]"},
     "cycles": {"min": 1},
     "arguments": {"min": 1}
     "description": "move the element on the nth stack position to the top of the stack",
     "instructions": [
       {"instruction": "push", "arguments": [1], "cycles": 1, "stack": {"before": [], "after": [1]}, "description": "Push the value 1 to the stack"},
       {"instruction": "push", "arguments": [3, 99], "cycles": 1, "stack": {"before": [], "after": [3, 99]}, "description": "Push the values 3 and 99 to the stack"},
       {"instruction": "push", "arguments": [85564, "0xad1234"], "cycles": 1, "stack": {"before": [85564, "0xad1234"], "after": ["1"]}, "description": "Push the values 85564 and 0xad1234 to the stack"},
     ]
  },
]
```

Regarding the visualization. It wasn't really about the individual instructions, but the program itself. When I need to double check the instructions I use a spreadsheet and do the trace by hand like this:

![image](https://user-images.githubusercontent.com/310139/214825395-25684fbd-1573-49ff-a231-4d8e422d881b.png)

**Comment by Dominik1999** [comment]
Those are also nice thoughts. Thanks @hackaugusto . I will add those to the options above.

> * When I'm writing assembly, I don't care about the binary instruction format. So it makes sense to have that in the JSON file, but I don't see any benefit for the playground cheat sheet.

Indeed that format is only chosen because we can create a simple table using this JSON, like we have now already in the playground. 

https://github.com/0xPolygonMiden/examples/blob/ef2a691cc555122c883214dad1ee6f883b71a25e/playground/src/components/InstructionTable.tsx#L3-L13
