### ISSUE TITLE
Tracking Issue: Get the Playground a good first entry point for Hackers end of March

### ISSUE THREAD

**Issue by Dominik1999** [0xPolygonMiden/examples#69]
We want to sponsor zkHack end of March. The Playground will be the entry point for Hackers to start working with the Miden VM.

The Playground is still missing some functionality. In addition, we should iterate over the design and visibility of explanations and links to relevant docs (Miden VM and the CLI). 

```[tasklist]
### Must Have - Functionality
- [ ] #52 
- [ ] #68 
- [ ] #67
```

```[tasklist]
### Must Have - Design / DevEx
- [ ] #59 
- [ ] #41
- [ ] https://github.com/0xPolygonMiden/examples/issues/85
- [ ] https://github.com/0xPolygonMiden/examples/issues/90
- [ ] https://github.com/0xPolygonMiden/examples/issues/86
- [ ] https://github.com/0xPolygonMiden/examples/issues/84
- [ ] https://github.com/0xPolygonMiden/examples/issues/75
- [ ] https://github.com/0xPolygonMiden/examples/issues/29
```

## Working group:
@Dominik1999 

<details>
<summary>Workflow</summary>

- Discussion should happen here or in the related sub-issues.
- PRs should only be merged by the coordinator to ensure everyone is able to review.
- Aim to complete reviews within 24 hours.
- When a related sub-issue is opened:
    - add it to the list of sub-issues in this tracking issue
- When opening a related PR:
    - request review from everyone in this working group
- When a sub-issue is completed:
    - close the related issue with a comment that links to the PR where the work was completed
</details>

### Coordinator: @Dominik1999 

<details>
<summary>Workflow</summary>

The working group coordinator ensures scope & progress tracking are transparent and accurate. They will:

- Merge approved PRs after all working group members have completed their reviews.
    - add the PR # to the relevant section of the current tracking PR.
    - close any completed sub-issue(s) with a comment that links to the PR where the work was completed
- Monitor workflow items and complete anything that slips through the cracks.
- Monitor scope to see if anything is untracked or unclear. Create missing sub-issues or initiate discussion as required.
- Monitor progress to see if there's anything which isn't moving forward. Initiate discussion as required.
- Identify PRs with especially significant changes and add @grjte and @bobbinth for review.
</details>
